---
spring:
  datasource:
    url: jdbc:mysql://localhost/tasks?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

---    
server:
  port: ${port:8030}

---    
activemq:
  url: tcp://127.0.0.1:61616
    
---    
document:
  queue:
    request: queue://document.request.queue
    response: queue://document.response.queue
    ack: queue://document.request.ack.queue
  file:
    output:
      folder: K:\java-dev\document-output-folder    
---
hazelcast:
  server:
    address: 127.0.0.1:5701
  group:
    server: hazelcast-group-server
    password: hazelcast-group-password